# Generated by Django 5.2 on 2025-04-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merek', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('tahun', models.IntegerField()),
                ('kilometer', models.IntegerField()),
                ('transmisi', models.CharField(choices=[('auto', 'Otomatis'), ('manual', 'Manual')], max_length=20)),
                ('jenis_bahan_bakar', models.CharField(choices=[('bensin', 'Bensin'), ('diesel', 'Diesel'), ('elektrik', 'Elektrik')], max_length=20)),
                ('mesin', models.CharField(max_length=50)),
                ('tempat_duduk', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='cars/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_service', models.DateField()),
                ('deskripsi', models.TextField()),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_histories', to='cars.cars')),
            ],
        ),
    ]
