# Generated by Django 5.2 on 2025-04-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='cars/images/'),
        ),
    ]
